# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please reload the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Centre for Strategic Futures
title-abbreviated: Centre for Strategic Futures
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Building a strategically agile public service ready to manage a complex and fast-changing environment
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

collections:
  our-work:
    output: true

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Site configuration
####################

# Resource Room and Pagination
resources_name: "media-centre"
paginate: 12
paginate_path: "/media-centre/page:num"

# Homepage sections
homepage_hero_i_want_to: false # if i_want_to is true, there will be no key highlights 
homepage_resources: true

# Feedback Form URL
feedback_form_url: "https://form.gov.sg/forms/pmo/5c36e6ed25bc5b0017433c85"

# FAQ URL
faq_url: "/faq/"
faq_url_external: false

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
